### ISSUE TITLE
Control car units

### ISSUE THREAD

**Issue by pietrodevo** [AlexIIL/TrainCraft-Ideas#6]
So, little idea that can be considered in future: control cab unit wagons to control operation train from the end opposite to the position of the locomotive to allow push-pull operation without the use of an additional locomotive, mainly in passenger trains, maybe simply by-passing controls like they are imputted directly to the loco in reverse way

**Comment by NitroxydeX** [comment]
Do you have a picture reference?

**Comment by pietrodevo** [comment]
Of course!

https://upload.wikimedia.org/wikipedia/commons/8/8a/SBB_IC_Bt_Oberbuchsiten_-_Oensingen.jpg
https://upload.wikimedia.org/wikipedia/commons/9/90/IC_Steuerwagen.jpg
http://farm8.static.flickr.com/7316/9330888301_286476c6b3.jpg
http://www.fotoferrovie.info/albums/userpics/10009/PilotaZ_9811_ALLFB.jpg
http://www.vitrains.it/sites/default/files/1091.jpg

I am referring to this kind of stuff:
https://en.wikipedia.org/wiki/Control_car

That basically let a train to operate this way:
https://en.wikipedia.org/wiki/Push%E2%80%93pull_train

One point that makes this kind of stuff even more interesting in traincraft than in real-life is the possibility to make automatization of trains more and more easier.
Let's suppose a train needs to stop at a station, the terminal station for its path, then come back again.
With two locos in minecraft, one for each side of the train, this is impossibile to make automatic ATM, also beacause you would need a standard lenght for trains to let each loco being on a sort of "command rail", for example to set which loco will now push and which instead will now pull. Eventually as for now it can be partially archieved having all the two locos in "passive" mode, so able to be pulled, but there are so many lags and glitches that makes it impossible.
The only thing to do is manually move the loco to the other side and then start again.
With a control car unit the loco is just one, so this makes things for automatization really amazing, you don't have to worry about train precise lenght to have stop and start commands, and at the same time makes things simplier also for normal manual operations, so that operations are really quick and easy

**Comment by NitroxydeX** [comment]
We should keep this in mind but I think some of the other trains have higher prio.

**Comment by pietrodevo** [comment]
Yes, that is sure, no priority, but something to consider and not so complicated

**Comment by AlexIIL** [comment]
Unfortunately I won't be implementing any trains or other carts - I'll leave that to railcraft or train craft itself
